spring:
  datasource:
    url: jdbc:mysql://172.17.127.135:3306/test?useSSL=false&useUnicode=true&CharacterEncoding=utf8
    username: root
    password: 123456

keycloak:
  auth-server-url: http://192.168.146.137:9090/auth
  realm: test
  resource: spring-boot-keycloak-webapi
  ssl-required: external
  credentials:
    secret: 64e7820c-6bb5-4ee0-86b9-219f86e87f2e
  use-resource-role-mappings: true
  bearer-only: false
  autodetect-bearer-only: true