server:
  port: 9028

spring:
  datasource:
    url: jdbc:mysql://172.17.127.135:3306/test?useSSL=false&useUnicode=true&CharacterEncoding=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false